// Copyright 2026 Laboratory for Underwater Systems and Technologies (LABUST)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Globalization;
using UnityEngine;

namespace Marus.Metocean
{
    /// <summary>
    /// Parsed live metrics from a Weather Display clientraw.txt feed.
    /// </summary>
    [Serializable]
    public struct WeatherDisplayData
    {
        [Tooltip("Weather station name extracted from field 32.")]
        public string stationName;

        [Tooltip("Last update timestamp reported by station in field 74.")]
        public string lastUpdateTime;

        [Tooltip("Ambient air temperature in Celsius (°C) from field 4.")]
        public float airTemperatureC;

        [Tooltip("Relative humidity percentage (0 - 100%) from field 5.")]
        public float humidityPercent;

        [Tooltip("Barometric pressure at sea level in hectopascals (hPa) from field 6.")]
        public float barometerHPa;

        [Tooltip("Average wind speed in meters per second (SI m/s) converted from field 1 (knots).")]
        public float windSpeedMs;

        [Tooltip("Average wind speed in km/h.")]
        public float windSpeedKmh;

        [Tooltip("Average wind speed in knots from field 1.")]
        public float windSpeedKnots;

        [Tooltip("Peak wind gust in meters per second (SI m/s) converted from field 2 (knots).")]
        public float windGustMs;

        [Tooltip("Peak wind gust in km/h.")]
        public float windGustKmh;

        [Tooltip("Peak wind gust in knots from field 2.")]
        public float windGustKnots;

        [Tooltip("Wind direction in degrees clockwise from North (0 - 360°) from field 3.")]
        public float windDirectionDegrees;

        [Tooltip("Daily accumulated rainfall in mm from field 7.")]
        public float dailyRainMm;

        [Tooltip("Current rain rate in mm/hour from field 10.")]
        public float rainRateMmHour;

        [Tooltip("Weather description or icon condition string from field 48 (e.g. 'Cloudy/Dry', 'Rain').")]
        public string weatherConditionText;
    }

    /// <summary>
    /// Metocean provider that ingests real-time weather observations from a Weather Display 'clientraw.txt' stream.
    /// <para>
    /// <b>Format Specification:</b><br/>
    /// The <c>clientraw.txt</c> data format is a real-time, space-delimited indexed text specification generated by
    /// the <i>Weather Display</i> software (by Brian Hamilton / Weather Display Live). It contains over 150 positional
    /// fields commonly used by personal and institutional weather networks (such as Davis Vantage stations,
    /// sibenik-meteo.hr, Pljusak, and Home Assistant).
    /// </para>
    /// <para>
    /// <b>Specification References:</b><br/>
    /// - Official Weather Display portal: <see href="http://www.weather-display.com"/><br/>
    /// - Saratoga-Weather Clientraw Field Specification: <see href="https://saratoga-weather.org/wxtemplates/clientraw-description.txt"/><br/>
    /// - Home Assistant Weather Display Integration: <see href="https://www.home-assistant.io/integrations/weatherdisplay/"/>
    /// </para>
    /// <para>
    /// <b>Key Positional Indices Parsed:</b><br/>
    /// - [0]: Header code (12345)<br/>
    /// - [1]: Current wind speed in knots (converted to SI m/s: knots * 0.514444)<br/>
    /// - [2]: Current wind gust in knots<br/>
    /// - [3]: Wind direction in degrees (0 - 360° clockwise from True North)<br/>
    /// - [4]: Outside air temperature in °C<br/>
    /// - [5]: Relative humidity in %<br/>
    /// - [6]: Barometric pressure in hPa<br/>
    /// - [7]: Daily accumulated rainfall in mm<br/>
    /// - [10]: Current rain rate in mm/hr<br/>
    /// - [32]: Station identifier string (e.g. 'Šubićevac-14:26:21')<br/>
    /// - [48]: Weather condition description string (e.g. 'Cloudy/Dry')<br/>
    /// - [74]: Station sample update timestamp<br/>
    /// - [150], [151]: Station latitude and longitude coordinates (if available)
    /// </para>
    /// </summary>
    [AddComponentMenu("MARUS/Metocean/Providers/Weather Display (clientraw.txt) Provider")]
    public class WeatherDisplayClientRawProvider : RestApiMetoceanProviderBase
    {
        [Header("Precipitation Scaling")]
        [Tooltip("Rain rate in mm/hr considered to be maximum (1.0) rain intensity. Standard heavy rain is ~25 mm/hr.")]
        [SerializeField] private float _maxRainRateMmHr = 25.0f;

        [Header("Live Weather Telemetry (Read Only)")]
        [SerializeField] private WeatherDisplayData _liveWeatherData;

        public override string ProviderName => "Weather Display (clientraw.txt)";

        /// <summary>
        /// Declares authoritative atmospheric parameters supplied by Weather Display.
        /// </summary>
        public override MetoceanDataFlags ProvidedData =>
            MetoceanDataFlags.Wind |
            MetoceanDataFlags.AirTemperature |
            MetoceanDataFlags.RelativeHumidity |
            MetoceanDataFlags.AtmosphericPressure |
            MetoceanDataFlags.Precipitation;

        /// <summary>
        /// Read-only snapshot of all parsed Weather Display telemetry.
        /// </summary>
        public WeatherDisplayData LiveWeatherData => _liveWeatherData;

        public WeatherDisplayClientRawProvider()
        {
            _apiUrl = "https://www.sibenik-meteo.hr/weather/amp/subicevac/clientraw.txt";
            _pollIntervalSeconds = 60.0f;
            _latitude = 43.73333; // Šubićevac, Šibenik default station location
            _longitude = 15.88333;
        }

        private void Reset()
        {
            _apiUrl = "https://www.sibenik-meteo.hr/weather/amp/subicevac/clientraw.txt";
            _pollIntervalSeconds = 60.0f;
            _latitude = 43.73333;
            _longitude = 15.88333;
        }

        protected override string BuildRequestUrl()
        {
            // clientraw.txt is a static direct file endpoint (no query parameters needed)
            return _apiUrl;
        }

        protected override bool TryParseResponse(string responseText, out MetoceanData data)
        {
            data = _currentData;
            if (string.IsNullOrWhiteSpace(responseText))
            {
                return false;
            }

            // clientraw.txt is a single space-separated string of indexed values
            string[] fields = responseText.Trim().Split(' ');

            // A valid clientraw.txt must contain at least 75 entries (full format contains over 150)
            if (fields.Length < 75)
            {
                return false;
            }

            // 1. Wind (fields 1, 2 in knots, field 3 in degrees)
            float windKnots = ParseFloat(fields[1]);
            float gustKnots = ParseFloat(fields[2]);
            float windDir = (ParseFloat(fields[3]) % 360f + 360f) % 360f;

            // Conversion: 1 knot = 0.514444 m/s (or 1.852 km/h)
            float windSpeedMs = windKnots * 0.5144444f;
            float gustSpeedMs = Mathf.Max(windSpeedMs, gustKnots * 0.5144444f);
            var wind = new WindData(windSpeedMs, windDir, gustSpeedMs);

            // 2. Atmosphere (fields 4: temp °C, 5: humidity %, 6: baro hPa)
            float tempC = ParseFloat(fields[4]);
            float humidity = Mathf.Clamp(ParseFloat(fields[5]), 0f, 100f);
            float barometer = ParseFloat(fields[6]);
            if (barometer < 100f) barometer = 1013.25f; // Fallback for invalid sensor reading

            // 3. Rain & Precipitation (fields 7: daily rain mm, 10: current rain rate mm/hr)
            float dailyRain = ParseFloat(fields[7]);
            float rainRate = fields.Length > 10 ? ParseFloat(fields[10]) : 0f;

            // Normalized rain intensity [0, 1]
            float rainIntensity = 0f;
            if (rainRate > 0.05f)
            {
                rainIntensity = Mathf.Clamp01(rainRate / Mathf.Max(1.0f, _maxRainRateMmHr));
            }
            else if (dailyRain > 0.1f && fields.Length > 48 && fields[48].IndexOf("rain", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                rainIntensity = 0.25f;
            }

            // 4. Station metadata & text
            string stationName = "Weather Station";
            if (fields.Length > 32)
            {
                string rawStation = fields[32];
                string[] parts = rawStation.Split('-');
                if (parts.Length > 0 && !string.IsNullOrEmpty(parts[0]))
                {
                    stationName = parts[0];
                }
            }

            string conditionText = fields.Length > 48 ? fields[48] : string.Empty;
            string updateTime = fields.Length > 74 ? fields[74] : string.Empty;

            // 5. Optional station GPS coordinates if available in extended fields (indices 150, 151)
            if (fields.Length > 151)
            {
                float stationLat = ParseFloat(fields[150]);
                float stationLon = ParseFloat(fields[151]);
                if (Mathf.Abs(stationLat) > 0.1f && Mathf.Abs(stationLon) > 0.1f)
                {
                    _latitude = stationLat;
                    _longitude = stationLon;
                }
            }

            // Record live telemetry snapshot
            _liveWeatherData = new WeatherDisplayData
            {
                stationName = stationName,
                lastUpdateTime = updateTime,
                airTemperatureC = tempC,
                humidityPercent = humidity,
                barometerHPa = barometer,
                windSpeedMs = windSpeedMs,
                windSpeedKmh = windKnots * 1.852f,
                windSpeedKnots = windKnots,
                windGustMs = gustSpeedMs,
                windGustKmh = gustKnots * 1.852f,
                windGustKnots = gustKnots,
                windDirectionDegrees = windDir,
                dailyRainMm = dailyRain,
                rainRateMmHour = rainRate,
                weatherConditionText = conditionText
            };

            // Construct new weather state, preserving fog, visibility, and cloudiness from current cache
            var weather = new WeatherStateData(
                airTemperature: tempC,
                atmosphericPressure: barometer,
                relativeHumidity: humidity,
                rainIntensity: rainIntensity,
                fogDensity: _currentData.Weather.fogDensity,
                visibility: _currentData.Weather.visibility,
                cloudCoverage: _currentData.Weather.cloudCoverage,
                wind: wind
            );

            data = new MetoceanData(_currentData.Ocean, weather, DateTime.UtcNow);
            return true;
        }

        private static float ParseFloat(string value)
        {
            if (float.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out float result))
            {
                return result;
            }
            return 0f;
        }
    }
}

